# Generated by Django 4.2 on 2023-05-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'blank': 'Ce champ est obligatoire.'}, max_length=255, unique=True, verbose_name='email adress')),
                ('nom', models.CharField(error_messages={'blank': 'Ce champ est obligatoire.'}, max_length=30, null=True)),
                ('prénom', models.CharField(error_messages={'blank': 'Ce champ est obligatoire.'}, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('niveau_1', models.BooleanField(default=False)),
                ('niveau_2', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=32)),
                ('confirmation', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userniv1',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.person')),
                ('identifiant_niveau_1', models.CharField(max_length=15)),
            ],
            bases=('account.person',),
        ),
        migrations.CreateModel(
            name='userniv2',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.person')),
                ('identifiant_niveau_2', models.CharField(max_length=15)),
            ],
            bases=('account.person',),
        ),
        migrations.CreateModel(
            name='userniv3',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.person')),
                ('identifiant_niveau_3', models.CharField(max_length=15)),
            ],
            bases=('account.person',),
        ),
    ]
